### ISSUE TITLE
Fix failing tests - ongoing effort

### ISSUE THREAD

**Issue by MaggieKimani1** [microsoft/OpenAPI.NET#1301]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1311
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1300
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1302
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1312
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1318
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1319
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1332
```
