### ISSUE TITLE
Resolve `JsonSchema` serialization

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET#1319]
```[tasklist]
### Tasks
- [x] Serializing a `JsonSchema` with reference
- [x] Serializing a `JsonSchema` without reference
- [x] Serialize `JsonSchema` `extensions` property properly
- [x] Serialize `AdditionalProperties` property in `JsonSchema` properly
- [ ] Recursive schema construction using `JsonSchemaBuilder` and serialization
- [ ] Add bool property `UnresolvedSchema` to `JsonSchema` via extension method. This will help in fixing JsonSchema validation test when object is just a `$ref`. (_This needs discussion_)
- [x] Fix V2 `JsonSchema` deserializer tests - `Parameter` and `Header` Deserializer tests (_caused by static field_)
- [x] Fix Reference validation tests failing because of `JsonSchema`
- [x] Fix `OpenApiSchemaTests` (_should be renamed JsonSchemaTests_) under V3 Readers Tests
```

**Comment by irvinesunday** [comment]
- `RecursiveRef` and `DynamicAnchor` don't seem to work for our use case when creating dynamic refs.
