### ISSUE TITLE
Use proxy reference objects in place of `OpenApiReference` objects when models have references

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET#1571]
Related to: https://github.com/microsoft/OpenAPI.NET/issues/1555

```[tasklist]
### Tasks
- [ ] Use proxy references during deserialization of models where models have references
- [ ] Validate models with proxy references as references and not as model classes.
- [ ] Properly serialize models which have proxy references objects as their `OpenApiReference`
