### ISSUE TITLE
v2 preview checklist

### ISSUE THREAD

**Issue by MaggieKimani1** [microsoft/OpenAPI.NET#1607]
- [x] Merge the Proxy reference PR
- [x] Pull the latest v2 changes on Components registry PR
- [x] Resolve anticipated merge conflicts:
     - [x] OpenApiReferenceResolver deletion in favor of HostDocumentResolver
     - [x] Moving Json schema reference resolution logic to HostDocumentResolver class 
     - [x] Update workspace test that calls `doc.ResolveReferences()`
     - [x] Resolve conflicts and failing tests - update verify output files for resolved Json schema $refs
 - [x] Merge components registry PR
- [x] Sync vnext changes with v2 branch
- [x] Merge v2 with vnext
- [ ] Bump up versions to preview and release

**Comment by KennethHoff** [comment]
What exactly are we waiting for here? The checklist seems complete other than the actual release
