### ISSUE TITLE
Implement native JSON schema support

### ISSUE THREAD

**Issue by MaggieKimani1** [microsoft/OpenAPI.NET#1727]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1733
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1763
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1793
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1765
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1789
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1790
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1791
- [x] Add host document to any model that can contain a reference.
- [x] Add a JsonSchemaReference proxy object for lazy reference resolution
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1764
- [ ] https://github.com/microsoft/OpenAPI.NET/issues/1812
```

**Comment by darrelmiller** [comment]
`type` property can be string or array in JSON Schema for 3.1

**Comment by captainsafia** [comment]
If it helps as a point of inspiration, here is the (internal) implementation of JsonSchema that might be a helpful basis for inspiration: https://github.com/dotnet/runtime/blob/c70791346cb716c02065c23d761d0743e30602ed/src/libraries/System.Text.Json/src/System/Text/Json/Schema/JsonSchema.cs
